[package]
name = "shigi"
version = "0.1.0"
authors = ["arata <arata04962@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.8.1", features = ["pdf"] }
clap = "2.33.1"